### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by spences10**
Added my Twitter bot into the repo as a folder :tada: :sweat:

### CODE REVIEW

**Comment by amandeepmittal** [comment]
You just have to add link to your Twitter Bot under the header `Twitter Bots`. No need to add it as a full module.

**Comment by spences10** [comment]
Derp! Ok, oh in the README? Ok, well it was a great learning experience anyways 🤓

**Comment by amandeepmittal** [comment]
Yeah, in the README.md file :)

**Comment by amandeepmittal** [comment]
I am closing this PR, and not merging it. You have to add another PR. Is that okay?

**Comment by spences10** [comment]
I notice the bots in the `Twitter Bots` section are the Twitter profiles, my bot it [my Twitter profile](https://twitter.com/ScottDevTweets)? You just want me to put my twitter URL on there or the link to my [GitHub repo](https://github.com/spences10/spences10-twitter-bot)?

Thanks

**Comment by amandeepmittal** [comment]
You can go for both. Actually that's a good idea. I am going to edit the README file and will put links to both the repo and to twitter accounts. :)

**Comment by spences10** [comment]
I'll pull the changes and submit again when you have made your changes :+1:

**Comment by amandeepmittal** [comment]
Done. Waiting for your PR now :)

**Pull request closed without merging**
