### PR TITLE
add awesome badge

### PR DESCRIPTION
**Pull request by amandeepmittal**
This repo needs awesome badge!

### CODE REVIEW

**Comment by spences10** [comment]
@amandeepmittal you waiting for sign off 😄

**Comment by amandeepmittal** [comment]
@spences10 Done!

**Comment by amandeepmittal** [comment]
@spences10 We should get more people to add their bots in this repo. It might help someone, someday.

**Comment by spences10** [comment]
@amandeepmittal yeah, agree :+1:

**Pull request merged**
